### ISSUE TITLE
Revisit stakeholder mapping, design next steps (eg. start land managers survey, researchers survey), identify engagement opportunities (T6.2 (ISRIC, ILVO, MU, BIOS, CREA, INRAE, CIRAD, ELO))

### ISSUE THREAD

**Issue by twoude** [soilwise-he/Project-management#12]
first new meeting half April, surveys sent out in April/ May research (or earlier) or 15 Oct-15 November for ELO, first version engagement plan ready before summer

@fennyvanegmond @RaduGiurgiu

**Comment by twoude** [comment]
@all: is this still open? At the right place? What needs to be done?

**Comment by RaduGiurgiu** [comment]
This needs to be broken down in subsequent tasks @isidorastojacic

**Comment by twoude** [comment]
As discussed: we will have a stakeholder meeting on 19 September. We will explain the project, show prototype, present stakeholder engagement plan and show the survey and next steps.
