### ISSUE TITLE
Start governance discussions (incl. vocabs by IUSS, GSP. SW repository, data gov) for SoilWise (ILVO)

### ISSUE THREAD

**Issue by twoude** [soilwise-he/Project-management#24]
@RaduGiurgiu 

asap (inventory of different types of governance needed in April), then make plan

**Comment by fennyvanegmond** [comment]
split in list of governance needed. then schedule of what lies where and what is still needed

**Comment by RaduGiurgiu** [comment]
There has been a meeting on this topic ( presentation Panos) so we can consider this done.
https://ilvo.sharepoint.com/:p:/s/HESoilWiseProject/EXZKZ4ubuptEiib69khMa74Ba5Y7Uk_cPoh7jKIw5p7_Bw?e=LXliPQ


There will be other issues that follow-up on this one.
