### ISSUE TITLE
transport post-it to Miro (ISRIC)

### ISSUE THREAD

**Issue by twoude** [soilwise-he/Project-management#28]
at the wednesday brugge meeting some post-in posters were created, these need to be ported to miro, to be able to communicate them to the wider group

**Comment by fennyvanegmond** [comment]
asked Ingrid to do this in next week/two weeks

**Comment by RaduGiurgiu** [comment]
this is done but should be followed-up with other tasks

**Comment by RaduGiurgiu** [comment]
> this is done but should be followed-up with other tasks

@twoude could you follow-up this?

**Comment by twoude** [comment]
The post-its are on MIRO  - I will create new issue to follow up

[SoilWise Milestone 1 Meeting, Bruges 27 March 2024 - Miro](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmiro.com%2Fapp%2Fboard%2FuXjVKd8wV1M%3D%2F&data=05%7C02%7Cthaisa.vanderwoude%40wur.nl%7C87a6feb73035418380f408dc936a46c9%7C27d137e5761f4dc1af88d26430abb18f%7C0%7C0%7C638547331869638871%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=Mz%2FDp7W%2FJLV%2B0ZpeEPZ08UggHmtosUkND5YeLKWmei0%3D&reserved=0).- this issue can be closed
