### ISSUE TITLE
T1.3 Meeting

### ISSUE THREAD

**Issue by RaduGiurgiu** [soilwise-he/Project-management#31]
It was discussed in the last ExBo (30.05) that T1.3 is at risk and needs a meeting to discuss the delayed actions.

#3 #2 #13

**Comment by twoude** [comment]
A Meeting took place on 25-06 with Christine, Vivianne, Nick, Radu and Kathi. @RaduGiurgiu what came out of the meeting?

**Comment by RaduGiurgiu** [comment]
> A Meeting took place on 25-06 with Christine, Vivianne, Nick, Radu and Kathi. @RaduGiurgiu what came out of the meeting?

It was a very fruitful meeting. Kathi joined and we discussed the Github and how it can be restructured, as well as how the process of requirements extraction can be better for the next iterations. There is a plan of action in which Kathi and Nick are working on better restructuring the requirements repos in git and Chrstine will use this for extracting the requirements from existing and future user stories (epics)

**Comment by RaduGiurgiu** [comment]
We proposed to further discuss with a focus on roles and responsibilities in the upcoming WP1 meeting (4th of July)
