### ISSUE TITLE
List of contributors to code

### ISSUE THREAD

**Issue by RaduGiurgiu** [soilwise-he/Project-management#44]
AP from the June exbo https://ilvo.sharepoint.com/:w:/s/HESoilWiseProject/EXsbyEpma_pOnuqkfMZVmMYByMmzHTiEl6H4FVltNc64ZQ?e=o6hIDR

**Comment by BerkvensNick** [comment]
a lis tof the leads of the different SWR technical components and the projectpartners who have declared they will collaborate to the development of these components can be found here:
https://github.com/soilwise-he/Soilwise-Project-Backlog/blob/main/components_and_repo.md
